services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    networks:
      - app-net
    volumes:
      - ./dist:/app/dist
  db:
    hostname: db
    env_file:
      - .env
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-net
    volumes:
      - philosophers:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  philosophers:

networks:
  app-net:
    driver: bridge