services:
  api:
    build: 
      context: .
      dockerfile: dev.dockerfile
    depends_on:
      - db
    networks:
      - app-net
    volumes:
      - ./dist:/app/dist
      - ./static:/app/static
    ports:
    - "8080:8080"
    - "5555:5555"
  db:
    hostname: db
    image: cockroachdb/cockroach:latest
    networks:
      - app-net
    volumes:
      - philosophers:/cockroach/cockroach-data
    ports:
      - "2657:2657"
      - "3000:3000"
    command: start-single-node --insecure --http-addr=db:3000

volumes:
  philosophers:

networks:
  app-net:
    driver: bridge