services:
  api:
    build: 
      context: .
      dockerfile: dev.dockerfile
    depends_on:
      - db
    networks:
      - app-net
    volumes:
      - ./dist:/app/dist
      - ./static:/app/static
    ports:
    - "8080:8080"
    - "5555:5555"
  db:
    hostname: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - app-net
    volumes:
      - philosophers:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  philosophers:

networks:
  app-net:
    driver: bridge