name: Melete DB update
on:
  workflow_dispatch:
    inputs:
      version:
        description: "semver version for sql dump"
        required: true
        type: string
jobs:
  db_update:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm ci
      - run: npm run compile
      - run: npm i -g prisma
      - run: prisma migrate reset --force
      - uses: tj-actions/pg-dump@v2.3
        with:
          database_url: ${{ secrets.DIRECT_URL }}
          path: "/melete_sql_dump.tar"
          options: "-F c"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl sftp shell
      - run: put /melete_sql_dump.tar /app/static
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
